jobs:
  include:
    - stage: build get
      script:
      - cd Docker
      - docker build -t ${DOCKER_USERNAME}/amanzi:latest -f Dockerfile-Amanzi-build .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $DOCKER_USERNAME/amanzi:latest
    - stage: test
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker run --rm $DOCKER_USERNAME/amanzi:latest /bin/bash -c "cd ~/amanzi_builddir/amanzi; ctest"
