language: cpp

sudo: false

services:
  - docker

branches:
  only:
  - master
  - alexis/docker

script:
  - cd Docker
  - echo "This would be the docker image build"
  - docker pull $DOCKER_USERNAME/amanzi:latest
  - docker run --rm $DOCKER_USERNAME/amanzi:latest "cd ~/amanzi_builddir/amanzi; ctest"

